### ISSUE TITLE
Sky3 is down

### ISSUE THREAD

**Issue by kien-truong** [vasia/gelly-partition-centric#6]
Hi Vasia,
Sky3 is down again. Can you tell someone to check it on Monday ?
Thanks.

**Comment by vasia** [comment]
Sorry about that :/ I'll see if I can get you sky1 or 2 in the meantime.

**Comment by vasia** [comment]
Sky3 seems to be up again. Please, try and let me know.

**Comment by kien-truong** [comment]
Yep. It's up again. Thanks, Vasia.
